# This is a basic workflow to help you get started with Actions

name: CI

env:
  GITHUB_TOKEN: ${{ github.token }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version:  3.9 # optional, default is 3.x
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64 # optional
          # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
#           token: ${{ github.token }} # optional, default is ${{ github.token }}
      
      - name: install pydpkg
        run: |
          pip install pydpkg
          git clone https://github.com/supermamon/dpkg-scanpackages-py.git
      
      - name: scan packages
        run: python ./dpkg-scanpackages-py/dpkg-scanpackages.py -m ./debs > Packages
          
      - name: GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # Git domain (default github.com)
#           domain: # optional, default is github.com
          # GitHub repository where assets will be deployed (default $GITHUB_REPOSITORY)
#           repo: # optional
          # Git branch where assets will be deployed
          target_branch: master # optional, default is gh-pages
          # Create incremental commit instead of doing push force
#           keep_history: # optional, default is false
          # Allow an empty commit to be created
#           allow_empty_commit: # optional, default is true
          # Build directory to deploy
          build_dir: ./
          # The committer name and email address
#           committer: # optional
          # The author name and email address
#           author: # optional
          # Commit message
#           commit_message: # optional
          # Write the given domain name to the CNAME file
#           fqdn: # optional
          # Allow Jekyll to build your site
#           jekyll: # optional, default is true
          # If enabled, nothing will be pushed
#           dry_run: # optional, default is false
          # Enable verbose output
#           verbose: true # optional, default is false 
